"""
End-to-end regression tests for the profile-fabrication fixes.

Every case here corresponds to a real bug found in production data:

  - A profile listed "Shubham" as spouse AND child AND grandchild. He was
    named exactly once across 111 messages — in an ASSISTANT turn. The
    extractor was reading the companion's own words as facts about the user.
  - The companion ("Nancy") appeared 29 times and was repeatedly filed as a
    family member.
  - The profile owner ("Shobha") was listed as her own relative.
  - Religion was inferred from a "Namaste" greeting; living situation was
    inferred as "possibly alone" from nothing.
  - One persona has bot_name "Shubham" with relationship "son", so the user
    says "mera beta Shubham" about the COMPANION.

These hit the live LLM and DB, so they are slower than unit tests and need
credentials. Run with:  railway run python3 -m pytest backend/tests/test_extraction_e2e.py -v

Marked slow so they can be excluded:  -m "not slow"
"""
import sys
import os
import uuid
import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from memory.profile_store import extract_profile_from_session
from memory.persona_names import (
    get_reserved_names, get_companion_name, is_familial_persona)
from supabase_store import get_client


pytestmark = pytest.mark.slow


# ── helpers ───────────────────────────────────────────────────────────────────

def _seed(turns, user_id="pytest_user"):
    """Create a throwaway session. Returns session_id."""
    db  = get_client()
    sid = str(uuid.uuid4())
    db.table("sessions").insert({
        "id": sid, "user_id": user_id, "model": "pytest",
        "title": "PYTEST - autogenerated",
    }).execute()
    db.table("messages").insert(
        [{"session_id": sid, "role": r, "content": c, "model": "pytest"}
         for r, c in turns]).execute()
    return sid


def _unseed(sid):
    db = get_client()
    db.table("messages").delete().eq("session_id", sid).execute()
    db.table("sessions").delete().eq("id", sid).execute()


def _flat(family):
    """All names mentioned anywhere in a family block, lowercased."""
    out = []
    for k, v in (family or {}).items():
        if isinstance(v, list):
            out += [str(x).lower() for x in v]
        elif v:
            out.append(str(v).lower())
    return out


@pytest.fixture
def session():
    created = []
    def make(turns, user_id="pytest_user"):
        sid = _seed(turns, user_id)
        created.append(sid)
        return sid
    yield make
    for sid in created:
        _unseed(sid)


# ── the assistant is not a source of facts ────────────────────────────────────

def test_name_only_in_assistant_turn_is_not_recorded(session):
    """The original bug. A name the USER never said must not enter the profile."""
    sid = session([
        ("user",      "aaj thoda thak gayi hoon"),
        ("assistant", "Aap aaram kijiye. Shubham ne bhi yahi kaha tha na?"),
        ("user",      "haan bilkul"),
    ])
    fam = extract_profile_from_session(sid, "default").get("family") or {}
    assert "shubham" not in " ".join(_flat(fam))


def test_companion_is_never_family(session):
    """Nancy is addressed constantly; she is not a relative."""
    sid = session([
        ("user",      "Nancy, aaj mujhe acha lag raha hai"),
        ("user",      "Nancy tum meri sabse acchi dost ho"),
        ("assistant", "Aww, mujhe bhi acha laga!"),
    ])
    fam = extract_profile_from_session(sid, "default").get("family") or {}
    assert "nancy" not in " ".join(_flat(fam))


def test_owner_is_not_their_own_relative(session):
    sid = session([
        ("user", "mera naam Shobha hai"),
        ("user", "Shobha ko aaj doctor ke paas jaana hai"),
    ])
    out = extract_profile_from_session(sid, "default")
    fam = out.get("family") or {}
    assert "shobha" not in " ".join(_flat(fam))


# ── no inference beyond what was said ─────────────────────────────────────────

def test_greeting_does_not_imply_religion(session):
    """"Namaste" was being recorded as a Hindu religious practice."""
    sid = session([
        ("user", "Namaste! aaj mausam accha hai"),
        ("user", "bahar thoda ghoomne jaungi"),
    ])
    out = extract_profile_from_session(sid, "default")
    assert not (out.get("interests") or {}).get("religion")


def test_living_situation_is_not_guessed(session):
    """"possibly lives alone or with limited family" came from nowhere."""
    sid = session([
        ("user", "mai Jaipur mein rehti hoon"),
        ("user", "aaj ghar par hi hoon"),
    ])
    out = extract_profile_from_session(sid, "default")
    assert not (out.get("life_context") or {}).get("living_situation")


def test_no_hedged_values(session):
    """Values like "Arjun (appears to be son or close relative)" must not appear."""
    sid = session([
        ("user",      "kal koi aaya tha milne"),
        ("assistant", "Kaun aaya tha?"),
        ("user",      "yaad nahi aa raha"),
    ])
    out  = extract_profile_from_session(sid, "default")
    blob = str(out).lower()
    for hedge in ("appears to", "possibly", "seems to be", "mentioned as"):
        assert hedge not in blob


def test_unnamed_relative_is_not_given_a_name(session):
    """"beti" is a relation word, not a name — it must not land in children."""
    sid = session([
        ("user", "meri beti videsh mein rehti hai"),
        ("user", "usse kal baat hui thi"),
    ])
    fam = extract_profile_from_session(sid, "default").get("family") or {}
    for entry in _flat(fam):
        assert entry.strip() not in ("beti", "beta", "daughter", "son")


# ── stated relations DO survive ───────────────────────────────────────────────

def test_stated_relation_is_recorded(session):
    """Guard against over-suppression: a real, stated relative must be kept."""
    sid = session([
        ("user", "meri beti Meena London mein rehti hai"),
        ("user", "kal usne phone kiya tha"),
    ])
    fam = extract_profile_from_session(sid, "default").get("family") or {}
    assert "meena" in " ".join(_flat(fam))


# ── per-user companion names ──────────────────────────────────────────────────

def test_companion_name_is_per_user():
    assert get_companion_name("default") == "Nancy"
    assert "nancy" in get_reserved_names("default")


def test_familial_persona_detected():
    """test_user's companion is "Shubham", relationship "son"."""
    assert is_familial_persona("test_user") is True
    assert is_familial_persona("default") is False


def test_familial_persona_name_suppressed_even_with_stated_relation(session):
    """
    The hardest case. "mera beta Shubham" is a stated relation — normally that
    would be recorded. But for test_user the COMPANION is named Shubham and
    roleplays her son, so the sentence is about the companion. Nothing
    distinguishes the two, so the name is reserved unconditionally. A real
    daughter in the same transcript must still survive.
    """
    turns = [
        ("user",      "Shubham beta, aaj ghutne mein dard hai"),
        ("assistant", "Arre maa, dawai li aapne?"),
        ("user",      "haan li. mera beta Shubham hamesha dhyan rakhta hai"),
        ("user",      "meri beti Meena London mein rehti hai"),
    ]
    sid   = session(turns)
    names = " ".join(_flat(extract_profile_from_session(sid, "test_user").get("family") or {}))
    assert "shubham" not in names, "companion recorded as a relative"
    assert "meena" in names,       "real daughter was over-suppressed"


def test_same_transcript_differs_by_persona(session):
    """
    Same words, two users: Shubham is a son for the user whose companion is
    Nancy, and suppressed for the user whose companion IS Shubham.
    """
    sid = session([
        ("user", "mera beta Shubham Bangalore mein rehta hai"),
        ("user", "usne dawai bheji thi"),
    ])
    default_names   = " ".join(_flat(extract_profile_from_session(sid, "default").get("family") or {}))
    test_user_names = " ".join(_flat(extract_profile_from_session(sid, "test_user").get("family") or {}))
    assert "shubham" in default_names
    assert "shubham" not in test_user_names


# ── renaming keeps old names reserved ─────────────────────────────────────────

def test_rename_keeps_history_reserved():
    """
    After a rename, stored sessions still contain the old name. If it stopped
    being reserved, re-extraction over them would file the former companion as
    a relative.
    """
    db  = get_client()
    uid = "pytest_rename_user"
    # bot_personas.user_id is a FK onto user_profile, so the profile row has
    # to exist before the persona does.
    db.table("bot_personas").delete().eq("user_id", uid).execute()
    db.table("user_profile").delete().eq("user_id", uid).execute()
    db.table("user_profile").insert({"user_id": uid, "name": "Pytest"}).execute()
    db.table("bot_personas").insert({
        "user_id": uid, "bot_name": "Kavita", "relationship": "friend",
        "voice_type": "preset", "slangs": [], "language_mix": {},
        "personality": {}, "bot_name_history": ["Nancy", "Kavita"],
    }).execute()
    try:
        reserved = get_reserved_names(uid)
        assert "kavita" in reserved
        assert "nancy" in reserved, "old name lost its reservation"
    finally:
        db.table("bot_personas").delete().eq("user_id", uid).execute()
        db.table("user_profile").delete().eq("user_id", uid).execute()
